// src/app/home/home.component.ts
import { Component } from '@angular/core';
import { AppStore } from './../app.store';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent {
  title = 'test-app';

  constructor(private appStore: AppStore) {} // Inject the AppStore service

  get counter() {
    return this.appStore.getCounter(); // Use the store's counter value
  }

  add() {
    this.appStore.add(); // Call the store's add method
  }

  subtract() {
    this.appStore.subtract(); // Call the store's subtract method
  }

  reset() {
    this.appStore.reset(); // Call the store's reset method
  }
}

<main class="flex min-h-screen flex-col items-center justify-between p-24">
    <h1 class="text-3xl">Hello World</h1>
    <div class="text-center">
      <h2>Your count is:</h2>
      <h2 class="text-7xl">{{ counter }}</h2>
    </div>
    <div class="flex flex-col gap-4">
      <button class="border-white border-4 w-64 h-12" (click)="add()">
        Increment
      </button>
      <button class="border-white border-4 w-64 h-12" (click)="subtract()">
        Decrement
      </button>
      <button class="border-white border-4 w-64 h-12" (click)="reset()">Reset</button>
      <button class='border-white border-4 w-64 h-12' routerLink="/test" routerLinkActive="active">Testpage</button>
    </div>
  </main>

// src/home.svelte
<script>
  import { Link } from "svelte-routing";
  import { counter } from "./lib/store";

  let count = 0;

  function increase() {
    counter.update(prev => prev += 1);
  }

  function reset() {
    counter.set(0);
  }

  counter.subscribe((prev_val) => count = prev_val);

</script>

<main class="flex min-h-screen flex-col items-center justify-between p-24">
  <h1 class="text-3xl">Hello World</h1>
  <div class="text-center">
    <h2>Your count is:</h2>
    <h2 class="text-7xl">{count}</h2>
  </div>
  <div class="flex flex-col gap-4">
    <button class="border-white border-4 w-64 h-12" on:click={increase}
      >Increment</button
    >
    <button class="border-white border-4 w-64 h-12" on:click={reset}
      >Reset</button
    >
    <Link to="/test" class="border-white border-4 w-64 h-12">
      <div class="flex place-items-center justify-center">
        <h1>Next Page</h1>
      </div>
    </Link>
  </div>
</main>
